### PR TITLE
Feature/allow encoding option

### LINKED ISSUE #43: Encoding error "Invalid byte sequence in UTF-8"
Hi @jdlubrano! 👋 
Thank you for the wonderful gem, it's been quite helpful for my use-case (which is streaming large JSONL files).
I'm running into an issue while streaming a particular file and I'm hoping for some help.

The exception raised is:
> **ArgumentError: invalid byte sequence in UTF-8**

The error occurs while trying to stream this particular file:

> https://github.com/praagyajoshi/dummy-repo/blob/master/bulk-9607413898.jsonl

The source of the file is somewhere else but I've uploaded to a demo repo for easy reproduction.

Interestingly enough, while streaming the file from the original URL, I was getting a slightly different exception "**<Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8>**" at https://github.com/jdlubrano/stream_lines/blob/main/lib/stream_lines/reading/stream.rb#L45.

I'm by no means an expert on encoding, but will be happy to provide any info needed.

Here is the backtrace of the exception:
```
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/stream.rb:41:in `split'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/stream.rb:41:in `extract_lines'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/stream.rb:32:in `block in stream_lines'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.0/lib/httparty/request.rb:152:in `block (2 levels) in perform'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:433:in `call_block'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:424:in `<<'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:383:in `block (2 levels) in inflate_adapter'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:382:in `inflate'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:382:in `block in inflate_adapter'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:433:in `call_block'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:424:in `<<'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:124:in `read'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:404:in `read'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:293:in `block in read_body_0'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:264:in `inflater'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:283:in `read_body_0'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:204:in `read_body'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.0/lib/httparty/request.rb:149:in `block in perform'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1503:in `block in transport_request'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:165:in `reading_body'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1502:in `transport_request'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1464:in `request'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1457:in `block in request'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:910:in `start'",
"/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1455:in `request'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.0/lib/httparty/request.rb:145:in `perform'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.0/lib/httparty.rb:594:in `perform_request'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.0/lib/httparty.rb:508:in `get'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/stream.rb:31:in `stream_lines'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/stream.rb:21:in `each'",
"/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/stream_lines-0.3.1/lib/stream_lines/reading/json_lines.rb:18:in `each'",
```

Thank you again for the help!

### PR DESCRIPTION
**Pull request by jdlubrano**
Fixes #43

### CODE REVIEW

**Comment by jdlubrano** [comment]
@praagyajoshi

Can you tell me whether this branch works with your example?  It is "working on my machine" 😀 , but I also noticed some intermittent invalid byte sequences at times.  Perhaps those were dependent on how my makeshift web server was splitting chunks or something like that.

I need to figure out how to test different character encodings, but, in general, if this code around encodings works, it seems straightforward enough to maintain.

**Comment by praagyajoshi** [comment]
Hi @jdlubrano!
Thank you for your continued work on this.

I tried it out 4 times and in that, it failed twice with the "invalid byte sequence in UTF-8" exception.
Intermittent - exactly as you mention.
Adding the stack trace below but I'm not sure it will be of much help.
```
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-43816f1cc75a/lib/stream_lines/reading/stream.rb:43:in `split'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-43816f1cc75a/lib/stream_lines/reading/stream.rb:43:in `extract_lines'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-43816f1cc75a/lib/stream_lines/reading/stream.rb:33:in `block in stream_lines'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.1/lib/httparty/request.rb:152:in `block (2 levels) in perform'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:433:in `call_block'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:424:in `<<'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:124:in `read'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:293:in `block in read_body_0'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:278:in `inflater'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:283:in `read_body_0'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:204:in `read_body'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.1/lib/httparty/request.rb:149:in `block in perform'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1503:in `block in transport_request'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:165:in `reading_body'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1502:in `transport_request'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1464:in `request'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1457:in `block in request'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:910:in `start'
/Users/praagyajoshi/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/http.rb:1455:in `request'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.1/lib/httparty/request.rb:145:in `perform'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.1/lib/httparty.rb:594:in `perform_request'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/gems/httparty-0.18.1/lib/httparty.rb:508:in `get'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-43816f1cc75a/lib/stream_lines/reading/stream.rb:32:in `stream_lines'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-43816f1cc75a/lib/stream_lines/reading/stream.rb:22:in `each'
/Users/praagyajoshi/.rvm/gems/ruby-2.5.3/bundler/gems/stream_lines-43816f1cc75a/lib/stream_lines/reading/json_lines.rb:18:in `each'
```

Other than that, the implementation looks good and simple enough to be configureable and maintable.
Nice one! 🙌

**Comment by jdlubrano** [comment]
Given that this is intermittent, which I can only guess has to do with where the server is chunking the streams, I need to think a bit about what we should do when we encounter an invalid byte sequence. I am wondering if we should go and get the next chunk. Hoping that the last part of the chunk that throws the invalid byte sequence error and the first part of the next chunk combine to create a valid byte sequence. I really don't know if that will work, though 🤔 .

**Comment by jdlubrano** [comment]
Ah! When I was debugging, I happened to notice that a chunk that threw an error was in fact split on the ü character. What I saw when debugging the chunk was Select Garmin N? when the original text was Select Garmin Nüvi GPS.

**Comment by jdlubrano** [comment]
@praagyajoshi I introduced some error handling in https://github.com/jdlubrano/stream_lines/pull/44/commits/4d267b01e814c92b2672b913275825855f994ecd, do you mind checking if it works for you?  It worked 10 out of 10 times for me, so I am hoping that we have a solution 🤞

**Comment by praagyajoshi** [comment]
> @praagyajoshi I introduced some error handling in [4d267b0](https://github.com/jdlubrano/stream_lines/commit/4d267b01e814c92b2672b913275825855f994ecd), do you mind checking if it works for you? It worked 10 out of 10 times for me, so I am hoping that we have a solution 🤞

Apologies about the delay in getting back to you, I was on vacation the past few days.  
Indeed this change seems to have worked. I tried 10 times as well and it worked everytime.  
Great detective work here, @jdlubrano!

**Comment by jdlubrano** [comment]
@praagyajoshi no worries about the delay.  Okay, I need to figure out how to write an automated test for this.  I will probably have time tomorrow or this weekend to try that.

**Pull request merged**
